---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: MusicKA 
  namespace: gop 
  annotations:
    flux.weave.works/tag.flask: glob:develop-v*
    flux.weave.works/automated: 'true'
  labels:
    role: music
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      role: music
  template:
    metadata:
      labels:
        role: music
    spec:
      containers:
      - name: nginx
        image: nginx:1.18-perl
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: nginx-proxy-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      - name: ML
        image: docker.io/cloudacademydevops/flaskapp:develop-v1.8.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5000
        env:
        - name: APP_NAME
          value: CloudAcademy.K8s.GitOps
        - name: APP_VERSION
          value: v1.0.4
      volumes:
      - name: nginx-proxy-config
        configMap:
          name: nginx-conf
