---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: MusicKA
  namespace: gop
  annotations:
    flux.weave.works/tag.flask: glob:develop-v*
    flux.weave.works/automated: 'true'
  labels:
    role: music
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      role: music
  template:
    metadata:
      labels:
        role: music
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
        - name: ML
          image: sanco/ml_flask:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: APP_NAME
              value: MusicKA.K8s
            - name: APP_VERSION
              value: v1.0
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        - name: collector
          image: sanco/collector_spring:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5001
          env:
            - name: APP_NAME
              value: MusicKA.K8s
            - name: APP_VERSION
              value: v1.0
      volumes:
        - name: nginx-proxy-config
          configMap:
            name: nginx-conf
